var cmdrList = [
    {
        image: 'ayli',
        fullname: 'Ayli, Eternal Pilgrim',
        colors: 'wb',
        level: '4',
        style: 'Fast Combo',
        wincons: 'Aetherflux Reservoir, Sanguine Bond',
        how_to_win: '<li>Gain life to buy time</li><li>Use Ad Nauseam to draw lots of cards</li><li>Use Aetherflux Reservoir or Sanguine Bond to finish the game</li>',
        decklist: ''
    }, {
        image: 'bruna',
        fullname: 'Bruna, Light of Alabaster',
        colors: 'wu',
        level: '5',
        style: 'Votron',
        wincons: 'Cmdr Dmg',
        how_to_win: '<li>Slow down your opponents so you have enough time to kill them with commander damage</li><li>Utilise Intuition with a combination of Corrupted Conscience, Eldrazi Conscription and Battle Mastery to instantly cobble together a one-shot commander</li><li>Use Stasis together with your vigilant Commander to buy you enough time to finish of all opponents</li>',
        decklist: ''
    }, {
        image: 'tazri',
        fullname: 'General Tazri',
        colors: 'wubrg',
        level: '9+',
        style: 'Fast Combo',
        wincons: 'Food Chain, THORacle',
        how_to_win: '<li>Use Food Chain in conjunction with a <abbr title="Cast From Exile">CFE</abbr> creature to generate infinite mana, the continuously cast and sacrifice Tazri to Food Chain while one of the other allies is on the field</li><li>Thassa\'s Oracle with Demonic consultation/Tainted Pact</li>',
        decklist: ''
    }, {
        image: 'radha',
        fullname: 'Grand Warlord Radha',
        colors: 'rg',
        level: '5',
        style: 'Elf Tribal, Storm',
        wincons: 'Beatdown',
        how_to_win: '<li>Utilise the haste effect from cards like Purphoros and Rythm of the Wild together with card draw to storm trough your library. Each new elf entering the battlefield sould be able to pay for itself or more<li>Generate ridiculous amounts of mana and use one of the pump effects to overrun your opponents</li>',
        decklist: ''
    }, {
        image: 'jhoira',
        fullname: 'Jhoira, Weatherlight Captain',
        colors: 'ur',
        level: '7-8',
        style: 'Artifact Storm',
        wincons: 'Aetherflux Reservoir, Labman',
        how_to_win: '<li>Get Jhoira on the field as fast as possible together with some cost reducers and cycle through your entire library in a single turn</li>',
        decklist: ''
    }, {
        image: 'lavinia',
        fullname: 'Lavinia of the Tenth',
        colors: 'wu',
        level: '5',
        style: 'Control',
        wincons: 'Approach of the Second Sunrise, Shark Typhoon',
        how_to_win: '<li>Turtle up and sit back. Counter whatever you absolutely need to get rid of and keep low until you\'ve developed a board state</li>',
        decklist: ''
    }, {
        image: 'maelstromWanderer',
        fullname: 'Maelstrom Wanderer',
        colors: 'urg',
        level: '6+',
        style: 'Big Mana',
        wincons: 'Beatdown',
        how_to_win: '<li>Use the early- and mid- game to ramp as much as possible to the just vomit half your deck ontu the board and overrun your opponents</li>',
        decklist: ''
    }, {
        image: 'mayael',
        fullname: 'Mayael the Anima',
        colors: 'wrg',
        level: '6',
        style: 'Battlecruiser',
        wincons: 'Beatdown',
        how_to_win: '<li>Use Mayael\'s ability or Lurking Predators/Defense of the Heart to get big scrary creatures out for cheap and build an untouchable board while going after your opponents</li>',
        decklist: ''
    }, {
        image: 'mishra',
        fullname: 'Mishra, Artificer Prodigy',
        colors: 'ubr',
        level: '4',
        style: 'Artifacts matter',
        wincons: '???',
        how_to_win: '<li>???</li><li>!??</li><li>Profit!</li>',
        decklist: ''
    }, {
        image: 'nath',
        fullname: 'Nath of the Gilt-Leaf',
        colors: 'bg',
        level: '7',
        style: 'Discard Stax',
        wincons: 'Beatdown',
        how_to_win: '<li>Hemper your opponents plans by shredding their hands and beat them down with the tokens generated by Nath</li>',
        decklist: ''
    }, {
        image: 'oona',
        fullname: 'Oona, Queen of the Fae',
        colors: 'ub',
        level: '8+',
        style: 'Fast Combo',
        wincons: 'Oona Exile-Mill',
        how_to_win: '<li>Assemble infinite mana and use Oona\'s ability to exile your opponents libraries, so the lose on their upkeep',
        decklist: ''
    }, {
        image: 'vannifar',
        fullname: 'Prime Speaker Vannifar',
        colors: 'ug',
        level: '8+',
        style: 'Fast Combo',
        wincons: 'Deck-Exile',
        how_to_win: '<li>Use Vannifar\'s Ability to assemble either Peregrine Drake + Deadeye Navigator or Temur Sabertooth + Eternal Witness</li><li>Repeatedly cast Reality Shift or Winds of Rebuke to exlie all opponents libraries</li>',
        decklist: ''
    }, {
        image: 'ruricThar',
        fullname: 'Ruric Thar, the Unbowed',
        colors: 'rg',
        level: '8',
        style: 'Stax/Battlecruiser',
        wincons: 'Kiki-Combo, Beatdown, Punishing Effects',
        how_to_win: '<li>Try to asselble a <abbr title="Kiki-Jiki + Great Oak Guardian">Kiki Combo</abbr></li><li>Assemble enough punishing effects linke Ruric Thar himself, where opponents hurt themselves with every action</li><li>Beat face with your numerous creatures</li>',
        decklist: ''
    }, {
        image: 'senTriplets',
        fullname: 'Sen Triplets',
        colors: 'wub',
        level: '7-8',
        style: 'Fast Combo',
        wincons: 'THORacle, Deck-Out',
        how_to_win: '<li>Either use Doomsday or assemble THORacle manually to win the game</li><li>Continuously tap Temple Bell with Dramatic Scepter Combo</li>',
        decklist: ''
    }, {
        image: 'slimefoot',
        fullname: 'Slimefoot, the Stowaway',
        colors: 'bg',
        level: '7',
        style: 'Tokens',
        wincons: 'Beatdown, Aristocrat drains',
        how_to_win: '<li>Create enough Saprolings and let them die to drain all opponents</li><li>Alternatively, use the Tokens to beat your opponents down</li>',
        decklist: ''
    }, {
        image: 'sythis',
        fullname: 'Sythis, Harvest\'s Hand',
        colors: 'wg',
        level: '6-7',
        style: 'Enchantress',
        wincons: 'SquirrelCraft, Boonweaver',
        how_to_win: '<li>Squirrel Nest + Earthcraft for infinite Tokens to beat down with</li><li>Boonweaver Giant + Pattern of Rebirth to set up Reanimator loops that contain [Reveillark|Karmic Guide|Angel of Glory\'s Rise]</li>',
        decklist: ''
    }, {
        image: 'tanaTymna',
        fullname: 'Tana, the Bloodsower / Tymna the Weaver',
        colors: 'wbrg',
        level: '9+',
        style: 'Stax',
        wincons: 'Kiki-Combo, Beatdown',
        how_to_win: '<li>Combo Kiki Jiki with Village Bell-Ringer, Felidar Guardian or Splintet Twin with Sharpshooter, Village Bell-Ringer<li><li>Pump your creatures with elesh Norn and beat face</li>',
        decklist: ''
    }, {
        image: 'trostani',
        fullname: 'Trostani, Selesnya\'s Voice',
        colors: 'wg',
        level: '5',
        style: 'Lifegain/Battlecruiser',
        wincons: 'Aetherflux Reservoir/Beatdown',
        how_to_win: '<li>Combine the general gameplan of amassing huge amounts of life with Aetherflux Reservoir</li><li>Assemble an army of tokens and overrun your opponents</li>',
        decklist: ''
    }, {
        image: 'uyo',
        fullname: 'Uyo, Silent Prophet',
        colors: 'u',
        level: '6',
        style: 'Spellslinger',
        wincons: 'Labman/Jace, Draw them out',
        how_to_win: '<li>Draw your entire library while Labman or Jace is on the field</li><li>Your commander allows you to potentially copy game-winning spells if your opponents cast them carelessly</li>',
        decklist: ''
    },
];